language: php
sudo: false
dist: trusty
php:
  - 5.6
  - 7.0
  - 7.1
  - nightly

# Declare which versions of WordPress to test against.
# Also declare whether or not to test in Multisite.
env:
  # Trunk
  # @link https://github.com/WordPress/WordPress
  - WP_VERSION=master WP_MULTISITE=0
  - WP_VERSION=master WP_MULTISITE=1

matrix:
  allow_failures:
    - php: nightly

before_install:
  - composer self-update

install:
  - composer --version
  - export PATH="$PATH:$HOME/.composer/vendor/bin"
  - composer global require "squizlabs/php_codesniffer=*"

before_script:
  - phpcs --version

script:
  - phpcs --standard=ruleset.xml --extensions=php -n -s .
