language: php
sudo: false
dist: trusty
php:
  - 5.6
  - 7.0
  - 7.1
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_install:
  - composer self-update

install:
  - composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require "squizlabs/php_codesniffer=*"

before_script:
  - phpcs --version

script:
  - phpcs --standard=ruleset.xml --extensions=php -n -s .
